services:
  - type: web
    name: malaria-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn --bind 0.0.0.0:$PORT wsgi:app --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: "10000"
      - key: PYTHONUNBUFFERED
        value: "true"
